### ISSUE TITLE
Why the timeout?

### ISSUE THREAD

**Issue by jimaek** [codepo8/detecting-adblock#1]
Hey, I really like your method of detecting if AdBlocker is enabled.
But I am curious, why did you add a timeout?
Wont this work exactly the same but faster?

```
(function(){
  var test = document.createElement('div');
  test.innerHTML = '&nbsp;';
  test.className = 'adsbox';
  document.body.appendChild(test);

    if (test.offsetHeight === 0) {
      alert(true);
    }
    test.remove();

})();
```

**Comment by codepo8** [comment]
I found without it the detection failed on localhost, that's all. Firefox
mostly.

**Comment by jimaek** [comment]
Strange. I assumed the opposite that you had issues on big slow websites.
I guess it needs testing to see how it works. Thanks!
