### ISSUE TITLE
Does not Working with UC Browser

### ISSUE THREAD

**Issue by mskian** [codepo8/detecting-adblock#6]
Hey I tried this Script work on Chrome & Mozilla Working Fine
but in UC Browser Mobile its does not work 
Any Solution? for detecting the Adblock in UC Browser?

**Comment by harryqt** [comment]
Redirect UC Browser to Chrome using JavaScript.

**Comment by codepo8** [comment]
What he said, UC browser doesn't execute JS, so it fails there.
